import type { Loc } from "./types";
import * as babylon from "@babel/parser";

export default {
  patterns: ["./**/*.{js,jsx}"],
  gitignore: true,
  encoding: "utf-8",
  parser: babylon,
  parserOptions: {
    allowImportExportEverywhere: true,
    allowAwaitOutsideFunction: true,
    allowReturnOutsideFunction: true,
    allowSuperOutsideMethod: true,
    sourceType: "unambiguous",
    plugins: [
      "jsx",
      "flow",
      "doExpressions",
      "objectRestSpread",
      // "decorators",
      "classProperties",
      "classPrivateProperties",
      "classPrivateMethods",
      "exportDefaultFrom",
      "exportNamespaceFrom",
      "asyncGenerators",
      "functionBind",
      "functionSent",
      "dynamicImport",
      "numericSeparator",
      "optionalChaining",
      "importMeta",
      "bigInt",
      "optionalCatchBinding",
      "throwExpressions",
      // "pipelineOperator",
      "nullishCoalescingOperator",
    ],
  },
  getLoc: (node: { loc: Loc }): Loc => node.loc,
};
